logging:
  level:
    com:
      memorynotfound: DEBUG
    org:
      springframework:
        security: INFO
        web: INFO
    root: WARN
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/etb_data
    username: etb_user
    password: etb123
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    serialization:
      write_dates_as_timestamps: false
server:
  port: 8888
swagger:
  ui:
    host: localhost:8888
